### PR TITLE
adds support for chunked media uploads

### PR DESCRIPTION
**Pull request by juanvillegas**
uploading images should be exactly the same, but it's been refactored to its own function.
it adds support for chunked video uploads. MIME type detection should probably be optional, not sure.

### CODE REVIEW

**Comment by YOzaz** [comment]
:+1: to this one.

**Comment by thujohn** [comment]
Hi.

Great job but I would prefer a non-breaking way to do this.

Maybe just by adding a uploadChunkedMedia() method?

**Comment by YOzaz** [comment]
@thujohn yeah, actually it would be better to have separate method for this.

**Comment by YOzaz** [comment]
@thujohn when do you think this will be updated and merged?
I've discovered it needs some amends - in this particular case, we're passing video file contents as one big string. In case video is, let's say, 500 Mb of size (it's real), we'll go out of memory. Maybe your package can accept local file path?

**Comment by scottybo** [comment]
Just in case someone else finds this thread, I've forked this package and added video support (docs for video near the bottom of the readme): https://github.com/scottybo/twitter

**Comment by atymic** [comment]
Hey @scottybo @juanvillegas 

I've created a fork (with issues enabled) & packagist release of the current version in the same namespace (unlike some of the other forks).

I plan to maintain this fork as i'm using it in a few projects.

https://github.com/atymic/laravel-twitter

I'd be happy to look through your PR if you'd like to PR it there.

I'd love to work with others on the package as well, so feel free to reach out.

If the original author does return, I'd be happy to merge our changes back into the mainline. If not, I plan to release v3 in a different namespace and fix a lot of the pre existing issues.

**Comment by atymic** [comment]
@scottybo would you be interested in updating this PR?

**Comment by atymic** [comment]
Closing due to 2.x going out of support.

**Pull request closed without merging**
