### PR TITLE
ZWNJ and Underscore are valid hashtag characters

### PR DESCRIPTION
**Pull request by masihyeganeh**
I'm not sure if there is anything else beside these two

### CODE REVIEW

**Comment by atymic** [comment]
Hey @masihyeganeh 

I've created a fork (with issues enabled) & packagist release of the current version in the same namespace (unlike some of the other forks).

I plan to maintain this fork as i'm using it in a few projects.

https://github.com/atymic/laravel-twitter

I'd be happy to look through your PR if you'd like to PR it there.

I'd love to work with others on the package as well, so feel free to reach out.

If the original author does return, I'd be happy to merge our changes back into the mainline. If not, I plan to release v3 in a different namespace and fix a lot of the pre existing issues.

**Comment by atymic** [comment]
Please rebase your PR and we'll merge it.

**Comment by masihyeganeh** [comment]
I'm sending a new PR.

**Comment by masihyeganeh** [comment]
Merge #275 instead

**Pull request closed without merging**
