### PR TITLE
Update Direct Message Trait

### PR DESCRIPTION
**Pull request by LakatosL**
Added getDmAll method, for retrieving all Direct Message events (both sent and received) within the last 30 days. Sorted in reverse-chronological order, using Twitter Api's new endpoint

### CODE REVIEW

**Comment by brich021** [comment]
👍for this.

**Comment by atymic** [comment]
Hey @LakatosL  

I've created a fork (with issues enabled) & packagist release of the current version in the same namespace (unlike some of the other forks).

I plan to maintain this fork as i'm using it in a few projects.

https://github.com/atymic/laravel-twitter

I'd be happy to look through your PR if you'd like to PR it there.

I'd love to work with others on the package as well, so feel free to reach out.

If the original author does return, I'd be happy to merge our changes back into the mainline. If not, I plan to release v3 in a different namespace and fix a lot of the pre existing issues.

**Comment by atymic** [comment]
Please rebase and we'll accept the PR

**Comment by atymic** [comment]
We've merged support for the new APIs into master, so will close this

**Pull request closed without merging**
