### PR TITLE
Chunked Media Upload

### PR DESCRIPTION
**Pull request by YOzaz**
Hello, I've updated @juanvillegas fork to give video upload possibility - but instead reading whole file into memory, I'm using local file path.
By the way, you can upload images to twitter using this method as well.
Also, included some important updates for Twitter library - 503 and others.

### CODE REVIEW

**Comment by YOzaz** [comment]
@thujohn updated to keep with upstream. Fixed some additional issues:
* Twitter API docs say, that status returned will be 2XX - so we should accept everything which is equal or below 299. Just for the future purposes.
* Fixed array bug $_response > $response.

**Comment by YOzaz** [comment]
And fixed support for Laravel 4.

**Comment by s1rc** [comment]
Any chance this will be approved and merged? I'd rather not have to switch packages for this feature.

**Comment by RykWaters** [comment]
@YOzaz or @s1rc This is a great bit of code. But have you included anything to check the status of the upload before a status can be posted? Tried adding to your code, but it seems that the way the urls are set means that we can't easily send get requests to the upload url. I'm assuming everyone has jumped ship to another package in order to upload videos?

**Comment by YOzaz** [comment]
@RykWaters I'm using my branch in production for a year now without any problems. Not sure I follow about checking status - do we need to do additional validation before proceeding with upload? In general, my branch is just +1 method and a switch.

**Comment by scottybo** [comment]
Just in case someone else finds this thread, I've forked this package and added video support (docs for video near the bottom of the readme): https://github.com/scottybo/twitter

**Comment by atymic** [comment]
Closing due to 2.x going out of support.

**Pull request closed without merging**
